#!/bin/bash
# set -x
set -e

PROJECT_DIR=$( cd "$( dirname "${BASH_SOURCE[0]}" )/../../" >/dev/null 2>&1 && pwd )
KUBERNETES_CONTEXT=default
NAMESPACE=spinnaker
BASE_DIR=/etc/spinnaker

EXTERNAL_IP=$(ip -4 route list 0/0 | awk '{print $3}')
MINNAKER_IP=$(cat /etc/spinnaker/.hal/public_endpoint)

# TODO: Add backups of existing configs

echo "Removing previous custom configs..."
> ${BASE_DIR}/.hal/external_services
printf "# Generated by external_service_setup.sh\n# For use in Minnaker" > ${BASE_DIR}/.hal/default/profiles/spinnaker-local.yml
printf "# Generated by external_service_setup.sh\n# For use in Dev Environment" > ${BASE_DIR}/.hal/spinnaker-local.yml
yq d -i ${BASE_DIR}/.hal/config deploymentConfigurations[0].deploymentEnvironment.customSizing

kubectl --context ${KUBERNETES_CONTEXT} -n ${NAMESPACE} get service -l app=spin -oname | awk -F'-' '{print $2}' > ${BASE_DIR}/.hal/all_services

while [ "$#" -gt 0 ]; do
  echo $1 >> ${BASE_DIR}/.hal/external_services
  shift
done

for svc in $(cat ${BASE_DIR}/.hal/all_services); do
  echo "Adding Minnaker reference to ${svc} to dev config..."
  PORT=$(kubectl get svc spin-${svc} -ojsonpath='{.spec.ports[0].port}')
  yq w -i ${BASE_DIR}/.hal/spinnaker-local.yml services.${svc}.baseUrl http://${MINNAKER_IP}:${PORT}
done

echo "Configuring Minnaker for these services:"
for svc in $(cat ${BASE_DIR}/.hal/external_services); do
  echo "Adding external reference to ${svc} to Minnaker config..."
  PORT=$(kubectl get svc spin-${svc} -ojsonpath='{.spec.ports[0].port}')
  yq w -i ${BASE_DIR}/.hal/default/profiles/spinnaker-local.yml services.${svc}.baseUrl http://${EXTERNAL_IP}:${PORT}
  echo "Scaling Minnaker ${svc} to 0 instances..."
  yq w -i ${BASE_DIR}/.hal/config deploymentConfigurations[0].deploymentEnvironment.customSizing.spin-${svc}.replicas 0
  echo "Updating external config to listen on 0.0.0.0 for ${svc} and removing custom baseUrl..."
  yq w -i ${BASE_DIR}/.hal/spinnaker-local.yml services.${svc}.host 0.0.0.0
  yq d -i ${BASE_DIR}/.hal/spinnaker-local.yml services.${svc}.baseUrl
done

echo "Generated deploymentConfigurations[0].deploymentEnvironment.customSizing:"
yq r ${BASE_DIR}/.hal/config deploymentConfigurations[0].deploymentEnvironment.customSizing

echo "Generated local ${BASE_DIR}/.hal/default/profiles/spinnaker-local.yml:"
echo "--------------"
cat ${BASE_DIR}/.hal/default/profiles/spinnaker-local.yml
echo "--------------"
echo "Place this file at '~/.spinnaker/spinnaker-local.yml' on your workstation"
echo "--------------"
cat ${BASE_DIR}/.hal/spinnaker-local.yml
echo "--------------"

echo "Applying changes:"
kubectl --context ${KUBERNETES_CONTEXT} -n ${NAMESPACE} exec -i halyard-0 -- sh -c "hal deploy apply"

# Printing again, just because...

echo "Generated deploymentConfigurations[0].deploymentEnvironment.customSizing:"
yq r ${BASE_DIR}/.hal/config deploymentConfigurations[0].deploymentEnvironment.customSizing

echo "Generated local ${BASE_DIR}/.hal/default/profiles/spinnaker-local.yml:"
echo "--------------"
cat ${BASE_DIR}/.hal/default/profiles/spinnaker-local.yml
echo "--------------"
echo "Place this file at '~/.spinnaker/spinnaker-local.yml' on your workstation"
echo "--------------"
cat ${BASE_DIR}/.hal/spinnaker-local.yml
echo "--------------"

# TODO: change overridebaseurls so we can do http things