# file: deploy-nginx.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: basic-deploy-to-kubernetes
spec:
  description: Basic nginx deploy to K3s
  application: &app-name armory-samples
  stages:
    - type: manualJudgment
      properties:
        name: Slack Chat Ops Approval
        refId: "1"
        failPipeline: true
        instructions: "Click Here ->  <a href=http://a594ebf7154144c8b840a5004b8ed253-1521180453.us-west-2.elb.amazonaws.com/productpage>Connect to Deployment Cluster?</a><p><b>Watch Video and Configure Armory Agent</b></p>"
    - type: deployManifest
      properties:
        name: Deploy text manifest
        refId: "2"
        requisiteStageRefIds: ["1"]
        account: spinnaker
        cloudProvider: kubernetes
        moniker:
          app: *app-name
        skipExpressionEvaluation: true
        source: text
        comments: This is a test for weekhooks
        manifests:
          - |
            apiVersion: apps/v1
            kind: Deployment
            metadata:
              name: new-microservice
              namespace: prod
              labels:
                app: nginx
            spec:
              replicas: 2
              selector:
                matchLabels:
                  app: nginx
              template:
                metadata:
                  labels:
                    app: nginx
                spec:
                  containers:
                  - name: nginx
                    image: nginx:1.14.2
                    ports:
                    - containerPort: 80
