# file: deploy-nginx.yaml
apiVersion: pacrd.armory.spinnaker.io/v1alpha1
kind: Pipeline
metadata:
  name: configure-slack-integration
spec:
  description: Click "Start Manual Execution" to the Right for Instructions 
  application: &app-name armory-samples
  stages:
    - type: manualJudgment
      properties:
        name: Configure Slack Integration
        refId: "1"
        failPipeline: true
        instructions: "Click Here ->  <a href=https://docs.armory.io/docs/armory-admin/notifications-slack-configure/>Configure Slack</a><p><b>Watch Video and Configure Slack</b></p>"
