apiVersion: spinnaker.armory.io/v1alpha2
kind: SpinnakerService
metadata:
  name: spinnaker
spec:
  spinnakerConfig:
    profiles:
      # deck has a special key "settings-local.js" for the contents of settings-local.js
      # this is a multiline string rather than a yml object and cannot be propertly 'patched'
      # All settings-local.js settings go in here
      deck:
        # Use the | YAML symbol to indicate a block-style multiline string
        settings-local.js: |
          window.spinnakerSettings.feature.kustomizeEnabled = true;
          window.spinnakerSettings.authEnabled = true;
